import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { Plus, Trash2, Loader2, Tag } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";

export default function Tags() {
  const [isCreateDialogOpen, setIsCreateDialogOpen] = useState(false);
  const [newTagName, setNewTagName] = useState("");
  
  const { data: tags, isLoading, refetch } = trpc.tags.list.useQuery();
  
  const createTag = trpc.tags.create.useMutation({
    onSuccess: () => {
      toast.success("Tag created successfully");
      setIsCreateDialogOpen(false);
      setNewTagName("");
      refetch();
    },
    onError: (error) => {
      toast.error(`Failed to create tag: ${error.message}`);
    },
  });
  
  const deleteTag = trpc.tags.delete.useMutation({
    onSuccess: () => {
      toast.success("Tag deleted");
      refetch();
    },
    onError: (error) => {
      toast.error(`Failed to delete tag: ${error.message}`);
    },
  });

  const handleCreateTag = () => {
    if (!newTagName) {
      toast.error("Please enter a tag name");
      return;
    }
    
    createTag.mutate({
      name: newTagName,
    });
  };

  return (
    <DashboardLayout>
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold text-foreground">Tags</h1>
            <p className="text-muted-foreground mt-1">
              Tag your content for easy searching (auto-generated by AI during import)
            </p>
          </div>
          
          <Dialog open={isCreateDialogOpen} onOpenChange={setIsCreateDialogOpen}>
            <DialogTrigger asChild>
              <Button>
                <Plus className="h-4 w-4 mr-2" />
                New Tag
              </Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Create Tag</DialogTitle>
                <DialogDescription>
                  Add a new tag for labeling content
                </DialogDescription>
              </DialogHeader>
              
              <div className="space-y-4 py-4">
                <div className="space-y-2">
                  <Label htmlFor="name">Tag Name</Label>
                  <Input
                    id="name"
                    placeholder="e.g., blonde, outdoor, lingerie"
                    value={newTagName}
                    onChange={(e) => setNewTagName(e.target.value)}
                  />
                </div>
              </div>
              
              <DialogFooter>
                <Button variant="outline" onClick={() => setIsCreateDialogOpen(false)}>
                  Cancel
                </Button>
                <Button onClick={handleCreateTag} disabled={createTag.isPending}>
                  {createTag.isPending && <Loader2 className="h-4 w-4 mr-2 animate-spin" />}
                  Create Tag
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </div>

        {isLoading ? (
          <div className="flex items-center justify-center py-12">
            <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
          </div>
        ) : tags && tags.length > 0 ? (
          <div className="flex flex-wrap gap-3">
            {tags.map((tag) => (
              <Card key={tag.id} className="inline-block">
                <CardContent className="p-4">
                  <div className="flex items-center gap-3">
                    <Badge variant="outline" className="text-base px-3 py-1">
                      <Tag className="h-4 w-4 mr-2" />
                      {tag.name}
                    </Badge>
                    <Button 
                      size="sm" 
                      variant="ghost"
                      onClick={() => {
                        if (confirm(`Delete tag "${tag.name}"? This won't delete the content.`)) {
                          deleteTag.mutate({ id: tag.id });
                        }
                      }}
                      disabled={deleteTag.isPending}
                    >
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        ) : (
          <Card>
            <CardContent className="flex flex-col items-center justify-center py-12">
              <Tag className="h-12 w-12 text-muted-foreground mb-4" />
              <h3 className="text-lg font-semibold mb-2">No Tags Yet</h3>
              <p className="text-muted-foreground text-center mb-4">
                Tags will be automatically generated by AI when you import content, or create them manually
              </p>
              <Button onClick={() => setIsCreateDialogOpen(true)}>
                <Plus className="h-4 w-4 mr-2" />
                Create Tag
              </Button>
            </CardContent>
          </Card>
        )}
      </div>
    </DashboardLayout>
  );
}
